IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 355
  ROI_HEIGHT: 40

XYCAR:
  # START_SPEED: 0.0
  # MAX_SPEED: 40.0
  # MIN_SPEED: 15.0
  # SPEED_CONTROL_THRESHOLD: 15.0
  # ACCELERATION_STEP: 0.05
  # DECELERATION_STEP: 0.1
  START_SPEED: 0.0
  MAX_SPEED: 30.0
  MIN_SPEED: 11.0
  SPEED_CONTROL_THRESHOLD: 15.0
  ACCELERATION_STEP: 0.3
  DECELERATION_STEP: 0.6

PID:
  P_GAIN: 1
  I_GAIN: 0.0006
  # I_GAIN: 0.00
  D_GAIN: 0.1
  # # P_GAIN: 0.5
  # P_GAIN: 0.75
  # # I_GAIN: 0.0006
  # I_GAIN: 0.0000
  # D_GAIN: 0.1
  # D_GAIN: 0.0000

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 1

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 150
  HIGH_THRESHOLD: 250

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 40
  MIN_LINE_LENGTH: 40
  MAX_LINE_GAP: 10
  Y_AXIS_MARGIN: 10

DEBUG: false

SAVE:
  ENABLE: false
  PATH: /home/nvidia/xycar_ws/src/LaneKeepingSystem/cv_imgs/detection/